# Generated by Django 3.2.18 on 2023-02-24 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spin',
            name='id',
        ),
        migrations.AlterField(
            model_name='spin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user_spins'),
        ),
    ]
