# Generated by Django 3.2.18 on 2023-05-25 06:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_resetuserpassword_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_image_file_path),
        ),
    ]
